### ISSUE TITLE
Suggestion on multiple windows.

### ISSUE THREAD

**Issue by ioggstream** [ioggstream/draft-polli-ratelimit-headers#6]
- [x]  `Reset` support for sliding window;
   *  see https://github.com/ioggstream/draft-polli-ratelimit-headers/blame/master/draft-polli-ratelimit-headers.md#L179
   * https://github.com/ioggstream/draft-polli-ratelimit-headers/blame/master/draft-polli-ratelimit-headers.md#L214

 - [x]  how to populate `Remaining` & `Reset` when multiple windows apply;

  * https://github.com/ioggstream/draft-polli-ratelimit-headers/blame/master/draft-polli-ratelimit-headers.md#L448
  * https://github.com/ioggstream/draft-polli-ratelimit-headers/blame/master/draft-polli-ratelimit-headers.md#L512

 - [x]  sub-second `Reset`: unsupported 
  
    * https://github.com/ioggstream/draft-polli-ratelimit-headers/blame/master/draft-polli-ratelimit-headers.md#L92

@alranel

**Comment by alranel** [comment]
I'd say explicitly that the timestamp specified in `Reset` can change across subsequent requests even before it is reached. This allows for sliding windows, penalties etc. I think it's important for client impementations to know that the `Reset` time should/could be evaluated _for each response_, instead of being cached until it expires. Let me know if this was clear enough, or I can provide an example.

**Comment by ioggstream** [comment]
Can you please add an example with requests?

Your considerations on caching Reset value is very interesting and it
should be added to the reasons for not using a timestamp value.

**Comment by ioggstream** [comment]
See #17

**Comment by ioggstream** [comment]
@alranel closed. Feel free to file another one if the current version do no address your concerns.

I added you to the Acknowledgements ;)
